### ISSUE TITLE
Manually entering dns+txt to issue a wildcard certificate

### ISSUE THREAD

**Issue by shoutmarble** [flobernd/docker-haproxy-acme#9]
I'm using Hostinger.com for my VPS provider.

I've been using Lego and getting acme certs doing a manual dns txt entry.
```
./lego -a --pem --email "twalsworth@gmail.com" --domains "landingdev.xyz" --domains "*.landingdev.xyz" --dns manual run
```

[9-use-dns-manual-mode](https://github.com/acmesh-official/acme.sh?tab=readme-ov-file#9-use-dns-manual-mode)
```
Add the following txt record:
Domain:_acme-challenge.example.com
Txt value:9ihDbjYfTExAYeDs4DBUeuTo18KBzwvTEjUnSwd32-c

Add the following txt record:
Domain:_acme-challenge.www.example.com
Txt value:9ihDbjxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Please add those txt records to the domains. Waiting for the dns to take effect.
```

Is there a way to issue a cert manually using a dns+txt entry?
```
services:
  haproxy-acme:
    image: ghcr.io/flobernd/haproxy-acme-dns01:latest
    container_name: haproxy-acme-dns01
    restart: unless-stopped
    environment:
      - "ACME_MAIL=mail@domain.com"
      - "ACME_DOMAIN=domain.com *.domain.com"
      - "ACME_DNS_API=dns_cf"
      - "CF_Token=<redacted>"
      - "CF_Zone_ID=<redacted>"
    volumes:
      - /docker_data/acme:/var/lib/acme:rw
    ports:
      - 80:80
      - 43:443
```
